### ISSUE TITLE
some broken links

### ISSUE THREAD

**Issue by permahorse** [jtomori/vfx_good_night_reading#5]
just randomly clicking stumbled upon these. i bet there are more

in Pipeline:
- A Pipeline for 800+ shots
- Cortex Open Source Framework 
- Managing thousands of assets for the Prince of Persia city of Alamut

**Comment by jtomori** [comment]
Thanks for reporting that.
I think there's not much I can do, since I am just storing links to external pages.

The easiest solution is to check whether those pages can be accessed via the Wayback Machine, for example [https://web.archive.org/web/20170825221852/http://moving-picture.com/UmbracoMedia/6302/managingthousandofassetsprincepersia.pdf](https://web.archive.org/web/20170825221852/http://moving-picture.com/UmbracoMedia/6302/managingthousandofassetsprincepersia.pdf).

**Comment by jtomori** [comment]
Since all items are stored in `library.yml` it would be possible to generate archived links with Wayback Machine's API, quick google search found [this module](https://pypi.org/project/waybackpy/).

For now I would just include a note on top of the page.
